[package]
name = "bounty_board"
edition = "2024.beta"
version = "0.1.0"
published-at = "0x0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
bounty_board = "0x0"
